# Fabric Dependencies:
## DynamicTrees Dependencies:
patchouli_project=393236
patchouli_file=7730941
dynamic_trees_file=8227325
dynamic_trees_version_range=>=1.7.0- <=1.7.2
## Tool/Utility Dependencies:
jade_file=8591528
jei_file=7391682
tagtooltips_file=6418039
## Seasons Dependencies:
glitchcore_file=8109791
serene_seasons_file=6182595
## Soil Dependencies:
moonlight_lib_file=7943879
grounded_version_range=>=1.21.1-0.2.0
immersive_weathering_version=V1.0.1-Fabric
immersive_weathering_version_range=>=1.0.0
