# NeoForge Dependencies:
## DynamicTrees Dependencies:
patchouli_project=306770
patchouli_file=6164617
# DynamicTrees
dynamic_trees_version=1.7.2
dynamic_trees_plus_version=1.3.2
dynamic_trees_version_range=[1.7.2,)
## Tool/Utility Dependencies:
jade_file=8591319
jei_file=7391682
suggestion_provider_fix_project=469647
suggestion_provider_fix_file=5598604
tagtooltips_file=6418051
## Seasons Dependencies:
glitchcore_file=8109792
serene_seasons_file=6182596
## Soil Dependencies:
moonlight_lib_file=8981395
grounded_version_range=[1.21.1-0.2.0,)
unearthed_unofficial_port_version=3.2.0
unearthed_version_range=[3.1.0,)
immersive_weathering_version=V1.0.4-NeoForge
immersive_weathering_version_range=[V1.0.0-NeoForge,)
